version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: nginx_web
    restart: unless-stopped
    ports:
      - '8081:80'
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    tty: true
    ports:
      - '3308:3306'  # Altere aqui para mapear a porta 3306 do container para a 3307 do host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravelContacts
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
